name: Total Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cloc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Code Lines Badge
        uses: Kherrisan/cloc-badge-action@1.0.1
