name: Total Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Count Lines of Code
        uses: Kherrisan/cloc-badge-action@v1.1.1
        with:
          directory: .
          output: LOC
